services:
  - type: web
    name: xmen-ttrpg-server
    env: node
    rootDirectory: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://projectcerebro.onrender.com
