-- ═══════════════════════════════════════════════════════════════
-- Migração 003 — Theme cards enriquecidos dos alunos dos Esquadrões
-- de Treino (Gen X, 14-16 anos). Cards = pilares de identidade + arco.
-- Cartas/tags dimensionadas por nível de perigo. NÃO toca em characters.
-- ═══════════════════════════════════════════════════════════════

BEGIN;

-- Anole [medio] — 4 cards, 15 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Lagarto Adaptável","poder":[{"texto":"Camuflagem Cromática","grau":4},{"texto":"Língua Preênsil Extensível","grau":4},{"texto":"Garras e Aderência a Superfícies","grau":4},{"texto":"Regeneração de Membros","grau":3},{"texto":"Agilidade Réptil","grau":3}],"fraqueza":[]},{"nome":"Orgulho de Victor","poder":[{"texto":"Assumidamente Gay e Confiante","grau":3},{"texto":"Sarcasmo como Escudo","grau":3},{"texto":"Ídolo dos Alunos Marginalizados","grau":2}],"fraqueza":[]},{"nome":"Irmão de Armas","poder":[{"texto":"Melhor Amigo de Rockslide","grau":3},{"texto":"Lealdade Feroz à Equipe","grau":3},{"texto":"Aluno do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Peso do Sobrevivente","poder":[],"fraqueza":[{"texto":"Culpa de Sobrevivente (Genosha)","grau":3},{"texto":"Aparência Monstruosa Julgada","grau":2},{"texto":"Impulsividade Adolescente","grau":2},{"texto":"Inexperiente em Combate Real","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Camuflagem Cromática","grau":4},{"texto":"Língua Preênsil Extensível","grau":4},{"texto":"Garras e Aderência a Superfícies","grau":4},{"texto":"Regeneração de Membros","grau":3},{"texto":"Agilidade Réptil","grau":3},{"texto":"Assumidamente Gay e Confiante","grau":3},{"texto":"Sarcasmo como Escudo","grau":3},{"texto":"Ídolo dos Alunos Marginalizados","grau":2},{"texto":"Melhor Amigo de Rockslide","grau":3},{"texto":"Lealdade Feroz à Equipe","grau":3},{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Culpa de Sobrevivente (Genosha)","grau":3},{"texto":"Aparência Monstruosa Julgada","grau":2},{"texto":"Impulsividade Adolescente","grau":2},{"texto":"Inexperiente em Combate Real","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Anole' AND is_global = TRUE;

-- Indra [medio] — 4 cards, 14 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Escudo Vivo","poder":[{"texto":"Armadura Retrátil de Placas","grau":4},{"texto":"Escudos Corporais Defensivos","grau":4},{"texto":"Resistência a Impactos","grau":3},{"texto":"Ancoragem Inabalável","grau":2}],"fraqueza":[]},{"nome":"Herança Jainista","poder":[{"texto":"Fé Hindu-Jainista Devota","grau":4},{"texto":"Pacifismo de Princípio","grau":4},{"texto":"Educação Rígida da Família","grau":3}],"fraqueza":[]},{"nome":"Jovem entre Dois Mundos","poder":[{"texto":"Senso de Dever","grau":3},{"texto":"Cortesia e Diplomacia","grau":3},{"texto":"Adolescente Mutante (14-16)","grau":1}],"fraqueza":[]},{"nome":"Relutância do Guerreiro","poder":[],"fraqueza":[{"texto":"Hesita em Usar Força Ofensiva","grau":3},{"texto":"Medo de Desonrar a Família","grau":3},{"texto":"Casamento Arranjado o Pressiona","grau":2},{"texto":"Novato sob Pressão","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Armadura Retrátil de Placas","grau":4},{"texto":"Escudos Corporais Defensivos","grau":4},{"texto":"Resistência a Impactos","grau":3},{"texto":"Ancoragem Inabalável","grau":2},{"texto":"Fé Hindu-Jainista Devota","grau":4},{"texto":"Pacifismo de Princípio","grau":4},{"texto":"Educação Rígida da Família","grau":3},{"texto":"Senso de Dever","grau":3},{"texto":"Cortesia e Diplomacia","grau":3},{"texto":"Adolescente Mutante (14-16)","grau":1},{"texto":"Hesita em Usar Força Ofensiva","grau":3},{"texto":"Medo de Desonrar a Família","grau":3},{"texto":"Casamento Arranjado o Pressiona","grau":2},{"texto":"Novato sob Pressão","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Indra' AND is_global = TRUE;

-- Kidogo [medio] — 4 cards, 13 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Gigante e Formiga","poder":[{"texto":"Alteração de Tamanho (formiga a gigante)","grau":5},{"texto":"Força Proporcional ao Tamanho","grau":4},{"texto":"Resistência Colossal quando Grande","grau":4},{"texto":"Furtividade quando Minúsculo","grau":3}],"fraqueza":[]},{"nome":"Coração Humilde","poder":[{"texto":"Humildade Genuína","grau":3},{"texto":"Humor Contagiante","grau":3},{"texto":"Faz Todos se Sentirem Bem","grau":2}],"fraqueza":[]},{"nome":"Raízes Africanas","poder":[{"texto":"Orgulho da Origem Suaíli","grau":3},{"texto":"Aluno do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Sombra da Própria Grandeza","poder":[],"fraqueza":[{"texto":"Subestima o Próprio Poder","grau":3},{"texto":"Autodepreciação Constante","grau":2},{"texto":"Timidez em Assumir Liderança","grau":2},{"texto":"Adolescente Inseguro","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Alteração de Tamanho (formiga a gigante)","grau":5},{"texto":"Força Proporcional ao Tamanho","grau":4},{"texto":"Resistência Colossal quando Grande","grau":4},{"texto":"Furtividade quando Minúsculo","grau":3},{"texto":"Humildade Genuína","grau":3},{"texto":"Humor Contagiante","grau":3},{"texto":"Faz Todos se Sentirem Bem","grau":2},{"texto":"Orgulho da Origem Suaíli","grau":3},{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Subestima o Próprio Poder","grau":3},{"texto":"Autodepreciação Constante","grau":2},{"texto":"Timidez em Assumir Liderança","grau":2},{"texto":"Adolescente Inseguro","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Kidogo' AND is_global = TRUE;

-- Loa [alto] — 5 cards, 19 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Toque Dissipador","poder":[{"texto":"Fase Através da Matéria Sólida","grau":5},{"texto":"Desintegração por Contato","grau":5},{"texto":"Rastros de Decomposição","grau":4},{"texto":"Intangibilidade Defensiva","grau":4},{"texto":"Ataque que Ignora Armaduras","grau":3}],"fraqueza":[]},{"nome":"Alma Havaiana","poder":[{"texto":"Espírito Livre e Praiano","grau":4},{"texto":"Misticismo das Ilhas","grau":3},{"texto":"Otimismo Contagiante","grau":3}],"fraqueza":[]},{"nome":"Provação Vampírica","poder":[{"texto":"Sobreviveu à Mordida de um Vampiro","grau":3},{"texto":"Amizade com Anole e Match","grau":3},{"texto":"Aluna do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Deslize Perigoso","poder":[],"fraqueza":[{"texto":"Poder Destrutivo que a Assusta","grau":3},{"texto":"Medo de Machucar Quem Ama","grau":3},{"texto":"Controle Instável sob Emoção","grau":2},{"texto":"Inexperiente em Batalha","grau":2}]},{"nome":"Sonhadora","poder":[{"texto":"Curiosidade Insaciável","grau":3},{"texto":"Lealdade aos Corsários","grau":2}],"fraqueza":[{"texto":"Distrai-se Facilmente","grau":2},{"texto":"Adolescente Impulsiva","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Fase Através da Matéria Sólida","grau":5},{"texto":"Desintegração por Contato","grau":5},{"texto":"Rastros de Decomposição","grau":4},{"texto":"Intangibilidade Defensiva","grau":4},{"texto":"Ataque que Ignora Armaduras","grau":3},{"texto":"Espírito Livre e Praiano","grau":4},{"texto":"Misticismo das Ilhas","grau":3},{"texto":"Otimismo Contagiante","grau":3},{"texto":"Sobreviveu à Mordida de um Vampiro","grau":3},{"texto":"Amizade com Anole e Match","grau":3},{"texto":"Aluna do Instituto Xavier","grau":2},{"texto":"Poder Destrutivo que a Assusta","grau":3},{"texto":"Medo de Machucar Quem Ama","grau":3},{"texto":"Controle Instável sob Emoção","grau":2},{"texto":"Inexperiente em Batalha","grau":2},{"texto":"Curiosidade Insaciável","grau":3},{"texto":"Lealdade aos Corsários","grau":2},{"texto":"Distrai-se Facilmente","grau":2},{"texto":"Adolescente Impulsiva","grau":2}]'::jsonb),
  danger = 'alto', updated_at = NOW()
  WHERE name = 'Loa' AND is_global = TRUE;

-- Rede (Network) [medio] — 4 cards, 13 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Rede Telepática","poder":[{"texto":"Transmissão de Pensamentos em Massa","grau":5},{"texto":"Leitura Telepática de Superfície","grau":4},{"texto":"Contato Mental à Distância","grau":3}],"fraqueza":[]},{"nome":"Geração Conectada","poder":[{"texto":"Trata Telepatia como Rede Social","grau":4},{"texto":"Antenada em Fofocas e Notícias","grau":3},{"texto":"Popular entre os Alunos","grau":2}],"fraqueza":[]},{"nome":"Voz do Grupo","poder":[{"texto":"Coordena a Equipe em Combate","grau":3},{"texto":"Empatia Crescente","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Imaturidade","poder":[],"fraqueza":[{"texto":"Invade a Privacidade Alheia","grau":3},{"texto":"Fala Demais na Hora Errada","grau":3},{"texto":"Ainda Amadurecendo","grau":2},{"texto":"Sem Preparo de Combate","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Transmissão de Pensamentos em Massa","grau":5},{"texto":"Leitura Telepática de Superfície","grau":4},{"texto":"Contato Mental à Distância","grau":3},{"texto":"Trata Telepatia como Rede Social","grau":4},{"texto":"Antenada em Fofocas e Notícias","grau":3},{"texto":"Popular entre os Alunos","grau":2},{"texto":"Coordena a Equipe em Combate","grau":3},{"texto":"Empatia Crescente","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2},{"texto":"Invade a Privacidade Alheia","grau":3},{"texto":"Fala Demais na Hora Errada","grau":3},{"texto":"Ainda Amadurecendo","grau":2},{"texto":"Sem Preparo de Combate","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Rede (Network)' AND is_global = TRUE;

-- Moça de Borracha [medio] — 4 cards, 13 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Corpo Elástico","poder":[{"texto":"Elasticidade e Maleabilidade Total","grau":5},{"texto":"Amortece Impactos","grau":4},{"texto":"Estica-se a Grandes Distâncias","grau":4},{"texto":"Molda-se a Qualquer Forma","grau":3}],"fraqueza":[]},{"nome":"Otimismo Blindado","poder":[{"texto":"Humor Físico e Palhaçadas","grau":4},{"texto":"Otimismo Inabalável","grau":3},{"texto":"Usa o Riso como Armadura","grau":3}],"fraqueza":[]},{"nome":"Espírito de Equipe","poder":[{"texto":"Adapta-se a Qualquer Situação","grau":3},{"texto":"Aluna do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Distração","poder":[],"fraqueza":[{"texto":"Desajeitada e Distraída","grau":3},{"texto":"Esconde Inseguranças no Humor","grau":2},{"texto":"Leva Combate Pouco a Sério","grau":2},{"texto":"Novata em Missões","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Elasticidade e Maleabilidade Total","grau":5},{"texto":"Amortece Impactos","grau":4},{"texto":"Estica-se a Grandes Distâncias","grau":4},{"texto":"Molda-se a Qualquer Forma","grau":3},{"texto":"Humor Físico e Palhaçadas","grau":4},{"texto":"Otimismo Inabalável","grau":3},{"texto":"Usa o Riso como Armadura","grau":3},{"texto":"Adapta-se a Qualquer Situação","grau":3},{"texto":"Aluna do Instituto Xavier","grau":2},{"texto":"Desajeitada e Distraída","grau":3},{"texto":"Esconde Inseguranças no Humor","grau":2},{"texto":"Leva Combate Pouco a Sério","grau":2},{"texto":"Novata em Missões","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Moça de Borracha' AND is_global = TRUE;

-- Boggart [medio] — 4 cards, 13 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Pesadelo Vivo","poder":[{"texto":"Metamorfose Aterrorizante","grau":4},{"texto":"Assume a Forma do Medo do Alvo","grau":4},{"texto":"Intimidação Psicológica","grau":3},{"texto":"Aparência Naturalmente Sinistra","grau":2}],"fraqueza":[]},{"nome":"Comediante Sombrio","poder":[{"texto":"Humor Negro e Brincalhão","grau":3},{"texto":"Leal aos Amigos Ferozmente","grau":3},{"texto":"Alívio Cômico da Equipe","grau":2}],"fraqueza":[]},{"nome":"Incompreendido","poder":[{"texto":"Coração Gentil sob a Máscara","grau":3},{"texto":"Aluno do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Rosto que Assusta","poder":[],"fraqueza":[{"texto":"Aspecto Assustador Permanente","grau":3},{"texto":"Rejeitado por Estranhos","grau":3},{"texto":"Insegurança com a Aparência","grau":2},{"texto":"Inexperiente em Combate","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Metamorfose Aterrorizante","grau":4},{"texto":"Assume a Forma do Medo do Alvo","grau":4},{"texto":"Intimidação Psicológica","grau":3},{"texto":"Aparência Naturalmente Sinistra","grau":2},{"texto":"Humor Negro e Brincalhão","grau":3},{"texto":"Leal aos Amigos Ferozmente","grau":3},{"texto":"Alívio Cômico da Equipe","grau":2},{"texto":"Coração Gentil sob a Máscara","grau":3},{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Aspecto Assustador Permanente","grau":3},{"texto":"Rejeitado por Estranhos","grau":3},{"texto":"Insegurança com a Aparência","grau":2},{"texto":"Inexperiente em Combate","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Boggart' AND is_global = TRUE;

-- Náiade [medio] — 4 cards, 12 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Senhora das Águas","poder":[{"texto":"Hidrocinese em Estado Líquido","grau":5},{"texto":"Manipula Grandes Volumes de Água","grau":4},{"texto":"Purifica ou Contamina Água","grau":3},{"texto":"Chicotes e Escudos de Água","grau":3}],"fraqueza":[]},{"nome":"Temperamento de Maré","poder":[{"texto":"Personalidade Fluida e Serena","grau":3},{"texto":"Adapta-se como a Corrente","grau":3}],"fraqueza":[]},{"nome":"Serenidade Aprendida","poder":[{"texto":"Calma que Acalma os Outros","grau":3},{"texto":"Aluna do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Águas Turvas","poder":[],"fraqueza":[{"texto":"Torna-se Turbulenta sob Pressão","grau":3},{"texto":"Depende de Fonte de Água","grau":3},{"texto":"Emoção Descontrola o Poder","grau":2},{"texto":"Novata em Batalha","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Hidrocinese em Estado Líquido","grau":5},{"texto":"Manipula Grandes Volumes de Água","grau":4},{"texto":"Purifica ou Contamina Água","grau":3},{"texto":"Chicotes e Escudos de Água","grau":3},{"texto":"Personalidade Fluida e Serena","grau":3},{"texto":"Adapta-se como a Corrente","grau":3},{"texto":"Calma que Acalma os Outros","grau":3},{"texto":"Aluna do Instituto Xavier","grau":2},{"texto":"Torna-se Turbulenta sob Pressão","grau":3},{"texto":"Depende de Fonte de Água","grau":3},{"texto":"Emoção Descontrola o Poder","grau":2},{"texto":"Novata em Batalha","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Náiade' AND is_global = TRUE;

-- Mira (Pinpoint) [medio] — 4 cards, 13 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Precisão Absoluta","poder":[{"texto":"Localiza Assinaturas Energéticas","grau":5},{"texto":"Identifica Pontos Fracos","grau":4},{"texto":"Nunca se Perde (literalmente)","grau":3},{"texto":"Percepção Tática Aguçada","grau":3}],"fraqueza":[]},{"nome":"Mente Metódica","poder":[{"texto":"Raciocínio Analítico e Frio","grau":4},{"texto":"Memória Espacial Perfeita","grau":3},{"texto":"Estrategista de Reconhecimento","grau":3}],"fraqueza":[]},{"nome":"Valor de Batedora","poder":[{"texto":"Indispensável em Missões","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Excesso de Confiança","poder":[],"fraqueza":[{"texto":"Arrogância pela Precisão","grau":3},{"texto":"Impaciência com os Menos Exatos","grau":2},{"texto":"Frágil em Combate Corpo a Corpo","grau":2},{"texto":"Inexperiente sob Fogo","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Localiza Assinaturas Energéticas","grau":5},{"texto":"Identifica Pontos Fracos","grau":4},{"texto":"Nunca se Perde (literalmente)","grau":3},{"texto":"Percepção Tática Aguçada","grau":3},{"texto":"Raciocínio Analítico e Frio","grau":4},{"texto":"Memória Espacial Perfeita","grau":3},{"texto":"Estrategista de Reconhecimento","grau":3},{"texto":"Indispensável em Missões","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2},{"texto":"Arrogância pela Precisão","grau":3},{"texto":"Impaciência com os Menos Exatos","grau":2},{"texto":"Frágil em Combate Corpo a Corpo","grau":2},{"texto":"Inexperiente sob Fogo","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Mira (Pinpoint)' AND is_global = TRUE;

-- Trovão [medio] — 4 cards, 12 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Voz de Trovão","poder":[{"texto":"Ondas de Choque Sônicas pela Voz","grau":5},{"texto":"Gera Trovões e Vibrações","grau":4},{"texto":"Ataque em Área Ensurdecedor","grau":3}],"fraqueza":[]},{"nome":"Alma Incandescente","poder":[{"texto":"Espírito Brasileiro Contagiante","grau":3},{"texto":"Paixão pelo Futebol e Samba","grau":2},{"texto":"Energia que Anima a Equipe","grau":2}],"fraqueza":[]},{"nome":"Coração Grande","poder":[{"texto":"Generosidade Calorosa","grau":3},{"texto":"Aluno do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Estouro","poder":[],"fraqueza":[{"texto":"Temperamento Explosivo","grau":3},{"texto":"Danos Acústicos Involuntários","grau":3},{"texto":"Fala Mais Alto que Pensa","grau":2},{"texto":"Novato Impulsivo","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Ondas de Choque Sônicas pela Voz","grau":5},{"texto":"Gera Trovões e Vibrações","grau":4},{"texto":"Ataque em Área Ensurdecedor","grau":3},{"texto":"Espírito Brasileiro Contagiante","grau":3},{"texto":"Paixão pelo Futebol e Samba","grau":2},{"texto":"Energia que Anima a Equipe","grau":2},{"texto":"Generosidade Calorosa","grau":3},{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Temperamento Explosivo","grau":3},{"texto":"Danos Acústicos Involuntários","grau":3},{"texto":"Fala Mais Alto que Pensa","grau":2},{"texto":"Novato Impulsivo","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Trovão' AND is_global = TRUE;

-- Umbra [medio] — 4 cards, 12 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Andarilha das Sombras","poder":[{"texto":"Viagem e Manipulação de Sombras","grau":5},{"texto":"Furtividade e Infiltração Absolutas","grau":4},{"texto":"Ataques a partir da Penumbra","grau":3},{"texto":"Camuflagem nas Trevas","grau":3}],"fraqueza":[]},{"nome":"Guardiã Silenciosa","poder":[{"texto":"Protege em Silêncio","grau":3},{"texto":"Observa Mais do que Age","grau":3}],"fraqueza":[]},{"nome":"Enigma","poder":[{"texto":"Mistério que Intriga a Equipe","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Prisão de Trevas","poder":[],"fraqueza":[{"texto":"Depende de Fontes de Sombra","grau":3},{"texto":"Introversão Isolante","grau":3},{"texto":"Dificuldade de Confiar","grau":2},{"texto":"Pouca Prática de Combate","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Viagem e Manipulação de Sombras","grau":5},{"texto":"Furtividade e Infiltração Absolutas","grau":4},{"texto":"Ataques a partir da Penumbra","grau":3},{"texto":"Camuflagem nas Trevas","grau":3},{"texto":"Protege em Silêncio","grau":3},{"texto":"Observa Mais do que Age","grau":3},{"texto":"Mistério que Intriga a Equipe","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2},{"texto":"Depende de Fontes de Sombra","grau":3},{"texto":"Introversão Isolante","grau":3},{"texto":"Dificuldade de Confiar","grau":2},{"texto":"Pouca Prática de Combate","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Umbra' AND is_global = TRUE;

-- Xenônio [medio] — 4 cards, 12 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Gás Nobre","poder":[{"texto":"Emissão de Gases e Energias Espectrais","grau":4},{"texto":"Cria Ilusões Gasosas","grau":4},{"texto":"Brilho Luminoso Desorientador","grau":3},{"texto":"Forma Gasosa Evasiva","grau":3}],"fraqueza":[]},{"nome":"Inconstância Nobre","poder":[{"texto":"Carisma Volátil e Cintilante","grau":3},{"texto":"Criatividade Imprevisível","grau":2}],"fraqueza":[]},{"nome":"Presença Efêmera","poder":[{"texto":"Surge e Some sem Aviso","grau":2},{"texto":"Aluno do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Instabilidade","poder":[],"fraqueza":[{"texto":"Humor Volátil (brilha e apaga)","grau":3},{"texto":"Dificuldade de se Fixar Física e Mentalmente","grau":3},{"texto":"Pouca Constância em Treino","grau":2},{"texto":"Inexperiente","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Emissão de Gases e Energias Espectrais","grau":4},{"texto":"Cria Ilusões Gasosas","grau":4},{"texto":"Brilho Luminoso Desorientador","grau":3},{"texto":"Forma Gasosa Evasiva","grau":3},{"texto":"Carisma Volátil e Cintilante","grau":3},{"texto":"Criatividade Imprevisível","grau":2},{"texto":"Surge e Some sem Aviso","grau":2},{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Humor Volátil (brilha e apaga)","grau":3},{"texto":"Dificuldade de se Fixar Física e Mentalmente","grau":3},{"texto":"Pouca Constância em Treino","grau":2},{"texto":"Inexperiente","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Xenônio' AND is_global = TRUE;

-- Bling! [medio] — 4 cards, 13 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Pele de Diamante","poder":[{"texto":"Esqueleto de Diamante Semi-Orgânico","grau":5},{"texto":"Arremessa Projéteis de Diamante","grau":4},{"texto":"Resistência Excepcional a Dano","grau":4},{"texto":"Corte Afiado no Combate","grau":3}],"fraqueza":[]},{"nome":"Brilho Próprio","poder":[{"texto":"Autoconfiança Deslumbrante","grau":4},{"texto":"Assumidamente Lésbica e Estilosa","grau":3},{"texto":"Presença de Estrela","grau":2}],"fraqueza":[]},{"nome":"Filha de Astros","poder":[{"texto":"Herança de Família Musical","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Fachada Reluzente","poder":[],"fraqueza":[{"texto":"Vaidade Exagerada","grau":3},{"texto":"Esconde Medos sob o Estilo","grau":2},{"texto":"Provoca Rivalidades","grau":2},{"texto":"Novata em Missões Reais","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Esqueleto de Diamante Semi-Orgânico","grau":5},{"texto":"Arremessa Projéteis de Diamante","grau":4},{"texto":"Resistência Excepcional a Dano","grau":4},{"texto":"Corte Afiado no Combate","grau":3},{"texto":"Autoconfiança Deslumbrante","grau":4},{"texto":"Assumidamente Lésbica e Estilosa","grau":3},{"texto":"Presença de Estrela","grau":2},{"texto":"Herança de Família Musical","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2},{"texto":"Vaidade Exagerada","grau":3},{"texto":"Esconde Medos sob o Estilo","grau":2},{"texto":"Provoca Rivalidades","grau":2},{"texto":"Novata em Missões Reais","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Bling!' AND is_global = TRUE;

-- Flubber [baixo] — 3 cards, 9 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Geleia Viva","poder":[{"texto":"Massa Gelatinosa e Elástica","grau":4},{"texto":"Maleabilidade Extrema","grau":3},{"texto":"Espreme-se por Qualquer Fresta","grau":3}],"fraqueza":[]},{"nome":"Alma Boba","poder":[{"texto":"Entusiasmo Contagiante","grau":4},{"texto":"Não Tem Um Osso Mau (literalmente)","grau":2},{"texto":"Aluno do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Trapalhão","poder":[],"fraqueza":[{"texto":"Desastre Desajeitado","grau":3},{"texto":"Alvo Fácil e Frágil","grau":3},{"texto":"Leva Pouco a Sério","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Massa Gelatinosa e Elástica","grau":4},{"texto":"Maleabilidade Extrema","grau":3},{"texto":"Espreme-se por Qualquer Fresta","grau":3},{"texto":"Entusiasmo Contagiante","grau":4},{"texto":"Não Tem Um Osso Mau (literalmente)","grau":2},{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Desastre Desajeitado","grau":3},{"texto":"Alvo Fácil e Frágil","grau":3},{"texto":"Leva Pouco a Sério","grau":2}]'::jsonb),
  danger = 'baixo', updated_at = NOW()
  WHERE name = 'Flubber' AND is_global = TRUE;

-- Foxx [alto] — 5 cards, 20 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Mística Infiltrada","poder":[{"texto":"Metamorfismo Perfeito (Mística)","grau":6},{"texto":"Imita Voz, Rosto e Impressões Digitais","grau":5},{"texto":"Disfarce Indetectável","grau":4},{"texto":"Mímica de Aparência e Gênero","grau":4},{"texto":"Regeneração Lenta","grau":3}],"fraqueza":[]},{"nome":"Espiã Sedutora","poder":[{"texto":"Espionagem e Sedução de Elite","grau":5},{"texto":"Provocação e Manipulação Constantes","grau":4},{"texto":"Leitura Fria de Pessoas","grau":3},{"texto":"Rede de Contatos no Submundo","grau":3}],"fraqueza":[]},{"nome":"Veterana da Irmandade","poder":[{"texto":"Séculos de Experiência em Combate","grau":4},{"texto":"Marcialista e Assassina Letal","grau":4},{"texto":"Sabotagem e Infiltração","grau":3},{"texto":"Nervos de Aço","grau":2}],"fraqueza":[]},{"nome":"Agente Duplo","poder":[{"texto":"Testa os Limites de Gambit","grau":3},{"texto":"Infiltrada entre os Alunos","grau":3}],"fraqueza":[{"texto":"Identidade Oculta","grau":3}]},{"nome":"Lealdade Incerta","poder":[],"fraqueza":[{"texto":"Agenda Secreta Própria","grau":4},{"texto":"Lealdade Questionável","grau":4},{"texto":"Frieza que Afasta Vínculos","grau":3},{"texto":"Manipuladora por Instinto","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Metamorfismo Perfeito (Mística)","grau":6},{"texto":"Imita Voz, Rosto e Impressões Digitais","grau":5},{"texto":"Disfarce Indetectável","grau":4},{"texto":"Mímica de Aparência e Gênero","grau":4},{"texto":"Regeneração Lenta","grau":3},{"texto":"Espionagem e Sedução de Elite","grau":5},{"texto":"Provocação e Manipulação Constantes","grau":4},{"texto":"Leitura Fria de Pessoas","grau":3},{"texto":"Rede de Contatos no Submundo","grau":3},{"texto":"Séculos de Experiência em Combate","grau":4},{"texto":"Marcialista e Assassina Letal","grau":4},{"texto":"Sabotagem e Infiltração","grau":3},{"texto":"Nervos de Aço","grau":2},{"texto":"Testa os Limites de Gambit","grau":3},{"texto":"Infiltrada entre os Alunos","grau":3},{"texto":"Identidade Oculta","grau":3},{"texto":"Agenda Secreta Própria","grau":4},{"texto":"Lealdade Questionável","grau":4},{"texto":"Frieza que Afasta Vínculos","grau":3},{"texto":"Manipuladora por Instinto","grau":2}]'::jsonb),
  danger = 'alto', updated_at = NOW()
  WHERE name = 'Foxx' AND is_global = TRUE;

-- Onyxx [medio] — 4 cards, 13 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Tanque de Granito","poder":[{"texto":"Corpo de Pedra Sólida","grau":5},{"texto":"Superforça e Resistência","grau":5},{"texto":"Muralha Viva em Combate","grau":4},{"texto":"Investida Devastadora","grau":3}],"fraqueza":[]},{"nome":"Coração de Ouro","poder":[{"texto":"Jeito Rapper e Fanfarrão","grau":3},{"texto":"Protetor Secreto dos Mais Fracos","grau":3},{"texto":"Presença Divertida","grau":2}],"fraqueza":[]},{"nome":"Grandalhão do Instituto","poder":[{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Condicionamento Bruto","grau":2}],"fraqueza":[]},{"nome":"Peso da Pedra","poder":[],"fraqueza":[{"texto":"Movimentos Lentos","grau":3},{"texto":"Esconde a Bondade por Vergonha","grau":2},{"texto":"Alvo por Ser Grande","grau":2},{"texto":"Inexperiente em Tática","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Corpo de Pedra Sólida","grau":5},{"texto":"Superforça e Resistência","grau":5},{"texto":"Muralha Viva em Combate","grau":4},{"texto":"Investida Devastadora","grau":3},{"texto":"Jeito Rapper e Fanfarrão","grau":3},{"texto":"Protetor Secreto dos Mais Fracos","grau":3},{"texto":"Presença Divertida","grau":2},{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Condicionamento Bruto","grau":2},{"texto":"Movimentos Lentos","grau":3},{"texto":"Esconde a Bondade por Vergonha","grau":2},{"texto":"Alvo por Ser Grande","grau":2},{"texto":"Inexperiente em Tática","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Onyxx' AND is_global = TRUE;

-- Garoto Chuva [medio] — 4 cards, 12 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Corpo de Água","poder":[{"texto":"Fisiologia Aquática","grau":4},{"texto":"Provoca Chuva Localizada","grau":4},{"texto":"Fluidez que Absorve Golpes","grau":3},{"texto":"Controle da Umidade","grau":3}],"fraqueza":[]},{"nome":"Céu Nublado","poder":[{"texto":"Sensibilidade Emocional Profunda","grau":3},{"texto":"Doçura Melancólica","grau":2}],"fraqueza":[]},{"nome":"Alma Sensível","poder":[{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Bondade Genuína","grau":2}],"fraqueza":[]},{"nome":"Tempestade Interior","poder":[],"fraqueza":[{"texto":"Chove Quando Fica Triste","grau":3},{"texto":"Melancolia que Afasta","grau":3},{"texto":"Frágil a Rejeições","grau":2},{"texto":"Novato Inseguro","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Fisiologia Aquática","grau":4},{"texto":"Provoca Chuva Localizada","grau":4},{"texto":"Fluidez que Absorve Golpes","grau":3},{"texto":"Controle da Umidade","grau":3},{"texto":"Sensibilidade Emocional Profunda","grau":3},{"texto":"Doçura Melancólica","grau":2},{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Bondade Genuína","grau":2},{"texto":"Chove Quando Fica Triste","grau":3},{"texto":"Melancolia que Afasta","grau":3},{"texto":"Frágil a Rejeições","grau":2},{"texto":"Novato Inseguro","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Garoto Chuva' AND is_global = TRUE;

-- Dríade [medio] — 4 cards, 12 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Voz da Floresta","poder":[{"texto":"Comunhão e Manipulação da Flora","grau":5},{"texto":"Fala com as Plantas","grau":4},{"texto":"Cresce Vegetação Instantânea","grau":3},{"texto":"Enredamento por Raízes e Cipós","grau":3}],"fraqueza":[]},{"nome":"Raiz Profunda","poder":[{"texto":"Serenidade de Floresta Antiga","grau":3},{"texto":"Ligação Espiritual com a Natureza","grau":3}],"fraqueza":[]},{"nome":"Guardiã Verde","poder":[{"texto":"Cuidado com os Vulneráveis","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Teimosia de Carvalho","poder":[],"fraqueza":[{"texto":"Teimosa e Imóvel quando Provocada","grau":3},{"texto":"Torna-se Espinhosa sob Estresse","grau":2},{"texto":"Depende de Ambiente com Vida","grau":2},{"texto":"Novata em Combate","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Comunhão e Manipulação da Flora","grau":5},{"texto":"Fala com as Plantas","grau":4},{"texto":"Cresce Vegetação Instantânea","grau":3},{"texto":"Enredamento por Raízes e Cipós","grau":3},{"texto":"Serenidade de Floresta Antiga","grau":3},{"texto":"Ligação Espiritual com a Natureza","grau":3},{"texto":"Cuidado com os Vulneráveis","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2},{"texto":"Teimosa e Imóvel quando Provocada","grau":3},{"texto":"Torna-se Espinhosa sob Estresse","grau":2},{"texto":"Depende de Ambiente com Vida","grau":2},{"texto":"Novata em Combate","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Dríade' AND is_global = TRUE;

-- Espinho [medio] — 4 cards, 12 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Chuva de Espinhos","poder":[{"texto":"Projeta Espinhos pelo Corpo","grau":5},{"texto":"Defesa e Ataque à Distância","grau":4},{"texto":"Manto Perfurante","grau":3},{"texto":"Cobertura de Supressão","grau":3}],"fraqueza":[]},{"nome":"Casca Defensiva","poder":[{"texto":"Lealdade Extrema aos Próximos","grau":2},{"texto":"Coragem Silenciosa","grau":2}],"fraqueza":[{"texto":"Personalidade Eriçada e Reclusa","grau":3}]},{"nome":"Desejo de Pertencer","poder":[{"texto":"Anseia por Aceitação","grau":2},{"texto":"Aluno do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Muros Internos","poder":[],"fraqueza":[{"texto":"Fecha-se num Casulo de Desconfiança","grau":3},{"texto":"Dificuldade de Fazer Amigos","grau":2},{"texto":"Autoimagem Negativa","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Projeta Espinhos pelo Corpo","grau":5},{"texto":"Defesa e Ataque à Distância","grau":4},{"texto":"Manto Perfurante","grau":3},{"texto":"Cobertura de Supressão","grau":3},{"texto":"Lealdade Extrema aos Próximos","grau":2},{"texto":"Coragem Silenciosa","grau":2},{"texto":"Personalidade Eriçada e Reclusa","grau":3},{"texto":"Anseia por Aceitação","grau":2},{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Fecha-se num Casulo de Desconfiança","grau":3},{"texto":"Dificuldade de Fazer Amigos","grau":2},{"texto":"Autoimagem Negativa","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Espinho' AND is_global = TRUE;

-- Espectro [medio] — 4 cards, 12 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Fantasma Andante","poder":[{"texto":"Intangibilidade","grau":5},{"texto":"Invisibilidade Parcial","grau":4},{"texto":"Atravessa Paredes","grau":4},{"texto":"Evasão e Fuga","grau":3}],"fraqueza":[]},{"nome":"Alma Distante","poder":[{"texto":"Humor Seco e Sussurrado","grau":3},{"texto":"Observador Perspicaz","grau":2}],"fraqueza":[]},{"nome":"Aparece na Hora Certa","poder":[{"texto":"Surge do Nada quando a Equipe Precisa","grau":3},{"texto":"Aluno do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Fuga Constante","poder":[],"fraqueza":[{"texto":"Foge dos Conflitos","grau":3},{"texto":"Introversão e Melancolia","grau":3},{"texto":"Distante e Esquivo","grau":2},{"texto":"Evita Compromisso","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Intangibilidade","grau":5},{"texto":"Invisibilidade Parcial","grau":4},{"texto":"Atravessa Paredes","grau":4},{"texto":"Evasão e Fuga","grau":3},{"texto":"Humor Seco e Sussurrado","grau":3},{"texto":"Observador Perspicaz","grau":2},{"texto":"Surge do Nada quando a Equipe Precisa","grau":3},{"texto":"Aluno do Instituto Xavier","grau":2},{"texto":"Foge dos Conflitos","grau":3},{"texto":"Introversão e Melancolia","grau":3},{"texto":"Distante e Esquivo","grau":2},{"texto":"Evita Compromisso","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Espectro' AND is_global = TRUE;

-- Três‑em‑Uma (Stepford Cuckoos) [alto] — 5 cards, 17 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Mente de Colmeia","poder":[{"texto":"Mente de Colmeia Telepática","grau":6},{"texto":"Telepatia de Nível Ômega em Conjunto","grau":5},{"texto":"Ilusões e Ataques Psíquicos","grau":4},{"texto":"Controle Mental Coordenado","grau":4},{"texto":"Leitura Simultânea de Muitas Mentes","grau":3}],"fraqueza":[]},{"nome":"Diamante Herdado","poder":[{"texto":"Forma de Diamante (como Emma)","grau":4},{"texto":"Elegância Fria e Calculista","grau":3},{"texto":"Filhas/Clones de Emma Frost","grau":3}],"fraqueza":[]},{"nome":"Trio Inseparável","poder":[{"texto":"Completam as Frases umas das Outras","grau":3},{"texto":"Falam como uma Só Voz","grau":3},{"texto":"Alunas de Elite do Instituto","grau":2}],"fraqueza":[]},{"nome":"Coração Partido","poder":[],"fraqueza":[{"texto":"Luto pelas Irmãs Perdidas (Sophie e Esme)","grau":4},{"texto":"Arrogância que Afasta","grau":3},{"texto":"Elo Enfraquece se Separadas","grau":3},{"texto":"Frieza Emocional","grau":2}]},{"nome":"Superioridade","poder":[{"texto":"Confiança Intelectual Imensa","grau":3}],"fraqueza":[{"texto":"Desprezo pelos Inferiores","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Mente de Colmeia Telepática","grau":6},{"texto":"Telepatia de Nível Ômega em Conjunto","grau":5},{"texto":"Ilusões e Ataques Psíquicos","grau":4},{"texto":"Controle Mental Coordenado","grau":4},{"texto":"Leitura Simultânea de Muitas Mentes","grau":3},{"texto":"Forma de Diamante (como Emma)","grau":4},{"texto":"Elegância Fria e Calculista","grau":3},{"texto":"Filhas/Clones de Emma Frost","grau":3},{"texto":"Completam as Frases umas das Outras","grau":3},{"texto":"Falam como uma Só Voz","grau":3},{"texto":"Alunas de Elite do Instituto","grau":2},{"texto":"Luto pelas Irmãs Perdidas (Sophie e Esme)","grau":4},{"texto":"Arrogância que Afasta","grau":3},{"texto":"Elo Enfraquece se Separadas","grau":3},{"texto":"Frieza Emocional","grau":2},{"texto":"Confiança Intelectual Imensa","grau":3},{"texto":"Desprezo pelos Inferiores","grau":2}]'::jsonb),
  danger = 'alto', updated_at = NOW()
  WHERE name = 'Três‑em‑Uma (Stepford Cuckoos)' AND is_global = TRUE;

-- Dust (Poeira) [medio] — 4 cards, 14 tags
UPDATE npcs SET
  data = jsonb_set(jsonb_set(COALESCE(data,'{}'::jsonb), '{temas}', '[{"nome":"Tempestade de Areia","poder":[{"texto":"Transforma-se em Nuvem de Areia Abrasiva","grau":5},{"texto":"Controle de Partículas Finas","grau":4},{"texto":"Esfola Inimigos como Lixa","grau":4},{"texto":"Forma Intangível Evasiva","grau":3}],"fraqueza":[]},{"nome":"Fé Inabalável","poder":[{"texto":"Muçulmana Devota (usa niqab)","grau":4},{"texto":"Determinação Silenciosa","grau":4},{"texto":"Modéstia de Princípio","grau":3}],"fraqueza":[]},{"nome":"Longe de Casa","poder":[{"texto":"Refugiada do Afeganistão","grau":3},{"texto":"Amizade Leal com Mercúrio","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2}],"fraqueza":[]},{"nome":"Reserva","poder":[],"fraqueza":[{"texto":"Timidez e Reserva","grau":3},{"texto":"Trauma de Cativeiro no Passado","grau":2},{"texto":"Estranheza Cultural a Isola","grau":2},{"texto":"Inexperiente em Combate","grau":2}]}]'::jsonb), '{tags}', '[{"texto":"Transforma-se em Nuvem de Areia Abrasiva","grau":5},{"texto":"Controle de Partículas Finas","grau":4},{"texto":"Esfola Inimigos como Lixa","grau":4},{"texto":"Forma Intangível Evasiva","grau":3},{"texto":"Muçulmana Devota (usa niqab)","grau":4},{"texto":"Determinação Silenciosa","grau":4},{"texto":"Modéstia de Princípio","grau":3},{"texto":"Refugiada do Afeganistão","grau":3},{"texto":"Amizade Leal com Mercúrio","grau":2},{"texto":"Aluna do Instituto Xavier","grau":2},{"texto":"Timidez e Reserva","grau":3},{"texto":"Trauma de Cativeiro no Passado","grau":2},{"texto":"Estranheza Cultural a Isola","grau":2},{"texto":"Inexperiente em Combate","grau":2}]'::jsonb),
  danger = 'medio', updated_at = NOW()
  WHERE name = 'Dust (Poeira)' AND is_global = TRUE;

COMMIT;

-- Resumo: 22 alunos atualizados, 295 tags no total (média 13.4/aluno).
